/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the Avnet MT3620 Starter Kit (SK) to the
// 'sample appliance' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the Avnet MT3620 SK, while other peripherals must be attached externally if needed.
// See https://aka.ms/AzureSphereHardwareDefinitions for more information on how to use hardware abstractions,
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../sample_appliance.json.  Do not edit it directly.

#pragma once
#include "mt3620.h"

// Pin 4 on X10 header.
#define SAMPLE_RGBLED_RED MT3620_GPIO42

// Pin 5 on X10 header.
#define SAMPLE_RGBLED_GREEN MT3620_GPIO43

// Pin 6 on X10 header.
#define SAMPLE_RGBLED_BLUE MT3620_GPIO6

// Signals present on X7 Header
#define SAMPLE_PMOD_UART MT3620_ISU3_UART

// Pin1 on X10 header
#define SAMPLE_PMOD_PIN8 MT3620_GPIO47

// Pin2 on X10 header
#define SAMPLE_PMOD_PIN9 MT3620_GPIO48

