/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This header contains the peripheral pinout definitions for the
// Avnet MT3620 Starter Kit (SK) Rev2.  Note that the Rev2 Starter
// Kit has 3 optional configurations that are selectable by relocating
// zero ohm resistors.  See the on-line user guide for more details
// <insert URL here>
//
// Click socket #2 can be configured for either a 4-wire UART (ISU1)
// which is the default, or an SPI (ISU1) interface.
// The default UART configuration has R59 and R60 populated with
// zero ohm resistors, and R61 and R62 unpopulated.
// Conversely the SPI configuration is selected by un-populating R59
// and R60, and fitting zero ohm resistors on locations R61 and R62.
//
// The un-populated UART/BLE Connector (PMOD) interface can be configured for either
// a type 4A UART (ISU1) which is the default, or a type 2A SPI (ISU1)
// interface.
// The default UART configuration has R39 and R50 populated with
// zero ohm resistors, and locations R41 and R52 unpopulated.
// Conversely the SPI configuration is selected by un-populating R39
// and R50, and fitting zero ohm resistors on locations R41 and R52.
//
// The Grove connector can be configured for either I2C (ISU2) which
// is the default, or a type 2A UART (ISU2) TX and RX only
// The default I2C configuration has R57, R53 and R55 populated with 
// zero ohm resistors, and R54 and R56 unpopulated.
// Conversely the UART configuration is selected by un-populating R57, R53,
// and R55, and fitting zero ohm resistors on locations R54 and R56
//

// This file is autogenerated from ../../avnet_mt3620_sk_rev2.json.  Do not edit it directly.

#pragma once
#include "avnet_aesms_mt3620_rev2.h"

// Application status LED uses GPIO4.
#define AVNET_MT3620_SK_APP_STATUS_LED_YELLOW AVNET_AESMS_PIN8_GPIO4

// WLAN status LED uses GPIO0.
#define AVNET_MT3620_SK_WLAN_STATUS_LED_YELLOW AVNET_AESMS_PIN9_GPIO0

// User LED Red channel uses GPIO8.
#define AVNET_MT3620_SK_USER_LED_RED AVNET_AESMS_PIN11_GPIO8

// User LED Green channel uses GPIO9.
#define AVNET_MT3620_SK_USER_LED_GREEN AVNET_AESMS_PIN12_GPIO9

// User LED Blue channel uses GPIO10.
#define AVNET_MT3620_SK_USER_LED_BLUE AVNET_AESMS_PIN13_GPIO10

// User BUTTON A uses GPIO12.
#define AVNET_MT3620_SK_USER_BUTTON_A AVNET_AESMS_PIN14_GPIO12

// User BUTTON B uses GPIO13.
#define AVNET_MT3620_SK_USER_BUTTON_B AVNET_AESMS_PIN15_GPIO13

// GPIO42 is exposed on SOCKET1 (AN).
#define AVNET_MT3620_SK_GPIO42 AVNET_AESMS_PIN30_GPIO42

// GPIO43 is exposed on SOCKET2 (AN).
#define AVNET_MT3620_SK_GPIO43 AVNET_AESMS_PIN31_GPIO43

// GPIO34 is exposed on SOCKET2 (INT) and UART/BLE Connector (PMOD) (Pin 1, CTS).
#define AVNET_MT3620_SK_GPIO34 AVNET_AESMS_PIN25_GPIO34

// GPIO35 is exposed on SOCKET2 (RST) and UART/BLE Connector (PMOD) (Pin 3, BLE Reset).
#define AVNET_MT3620_SK_GPIO35 AVNET_AESMS_PIN26_GPIO35

// GPIO31 is exposed twice on SOCKET2 (SCK) and (TX) and UART/BLE Connector (PMOD) (Pin 2, TX).
#define AVNET_MT3620_SK_GPIO31 AVNET_AESMS_PIN22_GPIO31

// GPIO33 is exposed twice on SOCKET2  (SDI) and (RX) and UART/BLE Connector (PMOD) (Pin 3, RX).
#define AVNET_MT3620_SK_GPIO33 AVNET_AESMS_PIN24_GPIO33

// GPIO32 is exposed on SOCKET2 (SDO) and UART/BLE Connector (PMOD) (Pin 4 RTS).
#define AVNET_MT3620_SK_GPIO32 AVNET_AESMS_PIN23_GPIO32

// GPIO0 is exposed on SOCKET1 (PWM).
#define AVNET_MT3620_SK_GPIO0 AVNET_AESMS_PIN5_GPIO0

// GPIO1 is exposed on SOCKET2 and UART/BLE Connector (PMOD) (Pin 9 BLE DFU).
#define AVNET_MT3620_SK_GPIO1 AVNET_AESMS_PIN6_GPIO1

// GPIO2 is exposed on SOCKET1 (RST).
#define AVNET_MT3620_SK_GPIO2 AVNET_AESMS_PIN7_GPIO2

// GPIO5 is exposed on SOCKET1 (INT).
#define AVNET_MT3620_SK_GPIO5 AVNET_AESMS_PIN9_GPIO5

// GPIO28 is exposed twice on SOCKET1 (SDI) and (RX).
#define AVNET_MT3620_SK_GPIO28 AVNET_AESMS_PIN20_GPIO28

// GPIO26 is exposed twice on SOCKET1. (SCK) and (TX)
#define AVNET_MT3620_SK_GPIO26 AVNET_AESMS_PIN18_GPIO26

// GPIO37 is exposed on SOCKET1 (SCL), SOCKET2 (SCL), GROVE Connector (Pin 1, SCL), and OLED Display Connector (Pin 3, SCL).
#define AVNET_MT3620_SK_GPIO37 AVNET_AESMS_PIN27_GPIO37

// GPIO38 is exposed on SOCKET1 (SDA), SOCKET2 (SDA), GROVE Connector (Pin 2, SDA),and OLED Display Connector (Pin 4, SDA).
#define AVNET_MT3620_SK_GPIO38 AVNET_AESMS_PIN28_GPIO38

// GPIO39 is exposed on UART/BLE Connector (PMOD) (Pin 7, BLE Status/Int).
#define AVNET_MT3620_SK_GPIO39 AVNET_AESMS_PIN16_GPIO39

// GPIO29 is exposed on SOCKET1. (CS)
#define AVNET_MT3620_SK_GPIO29 AVNET_AESMS_PIN21_GPIO29

// GPIO27 is exposed on SOCKET1. (SDO)
#define AVNET_MT3620_SK_GPIO27 AVNET_AESMS_PIN19_GPIO27

// PWM CONTROLLER 0: channel 0 is exposed on SOCKET1 (PWM), channel 1 is exposed on: SOCKET2 (PWM) and UART/BLE (PMOD) Connector (Pin 9 BLE DFU), channel 2 is exposed on: SOCKET1 (INT), SOCKET2 (INT) and UART/BLE (PMOD) Connector (Pin 7, BLE Status/Int) . Pins for this controller are shared with AVNET_MT3620_SK_GPIO0, AVNET_MT3620_SK_GPIO1 and AVNET_MT3620_SK_GPIO2. If this PWM controller is requested, none of these GPIOs can be used.
#define AVNET_MT3620_SK_PWM_CONTROLLER0 AVNET_AESMS_PWM_CONTROLLER0

// PWM CONTROLLER 1: channel 0 is used by Application Status LED, and channel 1 is used by WLAN status LED. Pins for this controller are shared with AVNET_MT3620_SK_APP_STATUS_LED_YELLOW and AVNET_MT3620_SK_WLAN_STATUS_LED_YELLOW. If this PWM controller is requested, none of these GPIOs can be used.
#define AVNET_MT3620_SK_PWM_CONTROLLER1 AVNET_AESMS_PWM_CONTROLLER1

// PWM CONTROLLER 2: channel 0 is used by User LED Red, channel 1 is used by User LED Green, channel 2 is used by User LED Blue. Pins for this controller are shared with AVNET_MT3620_SK_USER_LED_RED, AVNET_MT3620_SK_USER_LED_GREEN, and AVNET_MT3620_SK_USER_LED_BLUE. If this PWM controller is requested, none of these GPIOs can be used.
#define AVNET_MT3620_SK_PWM_CONTROLLER2 AVNET_AESMS_PWM_CONTROLLER2

// ADC CONTROLLER 0: channel 0 is used by Ambient Light Sensor, channel 1 is exposed on SOCKET1 (AN), channel 2 is exposed on SOCKET2 (AN). Pins for this controller are shared with AVNET_MT3620_SK_GPIO42 and AVNET_MT3620_SK_GPIO43. If this ADC controller is requested, none of these GPIOs can be used.
#define AVNET_MT3620_SK_ADC_CONTROLLER0 AVNET_AESMS_ADC_CONTROLLER0

// ISU0 UART is exposed on SOCKET1.
#define AVNET_MT3620_SK_ISU0_UART AVNET_AESMS_ISU0_UART

// ISU0 SPI is exposed on SOCKET1).
#define AVNET_MT3620_SK_ISU0_SPI AVNET_AESMS_ISU0_SPI

// ISU1 UART is exposed on SOCKET2 and UART/BLE Connector (PMOD).
#define AVNET_MT3620_SK_ISU1_UART AVNET_AESMS_ISU1_UART

// ISU1 SPI is exposed on SOCKET2 when R59, R60, R61 and R62 are modified.  See Users Guide.
#define AVNET_MT3620_SK_ISU1_SPI_CONFIGURABLE_SOCKET2 AVNET_AESMS_ISU1_SPI

// ISU1 SPI is exposed on UART/BLE Connector (PMOD) when R39, R50, R41 and R52 are modified.  See Users Guide.
#define AVNET_MT3620_SK_ISU1_SPI_CONFIGURABLE_UART_BLE AVNET_AESMS_ISU1_SPI

// ISU2 UART is also exposed on the Grove connector when Resistor locations R53, R54, R55, R56 and R57 are modified.  TX (Pin 2) RX (Pin 1)  See Users Guide.
#define AVNET_MT3620_SK_ISU2_UART_CONFIGURABLE_GROVE AVNET_AESMS_ISU2_UART

// ISU2 I2C is shared between on-device sensors, GROVE Connector, OLED DISPLAY Connector, SOCKET1, and SOCKET2.
#define AVNET_MT3620_SK_ISU2_I2C AVNET_AESMS_ISU2_I2C

