#
# This is an OpenAPI Specification for Device Communication Service's REST API.
# It uses v3.0.0 of the OpenAPI Specification format (OAS3).
#
# N.B. We use Semantic Versioning to define the version of this
# API. It is returned as HTTP response header in all communication.
#
# Given the version number in the MAJOR.MINOR.PATCH format, increment:
#     - MAJOR, when making incompatible API changes (e.g., removing an endpoint)
#     - MINOR, when adding functionality in a backwards-compatible way.
#     - PATCH, when fixing a bug in a backwards-compatible way.
#
# [Version History]
#

openapi: "3.0.0"

info:
  version: 1.0.0
  title: Azure Sphere Device Communication Service REST API
  description: REST API exposed by Azure Sphere device communication service

servers:
  - url: http://localhost:48938

paths:
  /api/service/devices:
    get:
      operationId: "getDevices"
      summary: "Enumerate devices managed by the Device Communication Service"
      responses:
        200:
          description: "List of Device IP Addresses and Connection Paths"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceConnectionInfoList"
  /api/service/devices/rescan:
    put:
      operationId: "rescanAttachedDevices"
      summary: "Enumerate number of attached devices managed by the Device Communication Service"
      responses:
        200:
          description: "Number of attached devices"
          content:
            application/json:
              schema:
                type: integer
components:
  schemas:
    DeviceConnectionInfo:
      type: object
      properties:
        IpAddress:
          type: string
          example: "192.168.35.2"
        DeviceConnectionPath:
          type: string
          example: "223"
      required:
        - IpAddress
        - DeviceConnectionPath
    DeviceConnectionInfoList:
      type: array
      items:
        $ref: "#/components/schemas/DeviceConnectionInfo"
