/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the Avnet AE-SMS-MT3620 module to the
// MCU-to-cloud hardware reference solution.
// See https://aka.ms/AzureSphereHardwareDefinitions for more information on how to use hardware abstractions,
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../msft_m2c_hwref.json.  Do not edit it directly.

#pragma once
#include "avnet_aesms_mt3620.h"

// ISU0 UART
#define MSFT_M2CHWREF_ISU0_UART AVNET_AESMS_ISU0_UART

// ISU1 UART (not connected on the hardware reference board)
#define MSFT_M2CHWREF_ISU1_UART AVNET_AESMS_ISU1_UART

// Red channel of on-board RGB LED
#define MSFT_M2CHWREF_RGBLED_RED AVNET_AESMS_PIN5_GPIO0

// Green channel of on-board RGB LED
#define MSFT_M2CHWREF_RGBLED_GREEN AVNET_AESMS_PIN6_GPIO1

// Blue channel of on-board RGB LED
#define MSFT_M2CHWREF_RGBLED_BLUE AVNET_AESMS_PIN7_GPIO2

