/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MCU-to-cloud hardware reference board to the
// soda machine as implemented in the low-power MCU-to-cloud software reference solution.
// See https://aka.ms/AzureSphereHardwareDefinitions for more information on how to use hardware abstractions,
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../soda_machine.json.  Do not edit it directly.

#pragma once
#include "msft_m2c_hwref.h"

// UART for MT3620<->STM32 comms
#define SODAMACHINE_STM32_UART MSFT_M2CHWREF_ISU0_UART

// Debug UART (not available on the hardware reference board)
#define SODAMACHINE_DEBUG_UART MSFT_M2CHWREF_ISU1_UART

// Red channel of RGB status LED
#define SODAMACHINE_RGBLED_RED MSFT_M2CHWREF_RGBLED_RED

// Green channel of RGB status LED
#define SODAMACHINE_RGBLED_GREEN MSFT_M2CHWREF_RGBLED_GREEN

// Blue channel of RGB status LED
#define SODAMACHINE_RGBLED_BLUE MSFT_M2CHWREF_RGBLED_BLUE

