/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the Avnet MT3620 Guardian 100 (G100)

// This file is autogenerated from ../../avnet_g100.json.  Do not edit it directly.

#pragma once
#include "avnet_aesms_mt3620.h"

// G100: LED 1.
#define LED_1 AVNET_AESMS_PIN11_GPIO8

// G100: LED 2.
#define LED_2 AVNET_AESMS_PIN12_GPIO9

// G100: LED 3.
#define LED_3 AVNET_AESMS_PIN13_GPIO10

// G100 USB Type B Connector.
#define EXTERNAL_UART AVNET_AESMS_ISU1_UART

